name: Run-All-Test

on:
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install & npm run test:ci
      - run: cd test*/test* & npm install & npm run test:ci
